### ISSUE TITLE
Add support for shiftout operation

### ISSUE THREAD

**Issue by Herbstein** [christophediericx/ArduinoDriver#12]
This would be very useful when working with shift registers.

**Comment by christophediericx** [comment]
Hi Herbstein,

Thank you for your interest in this library. I agree, this would be a useful feature indeed. I will try to implement it in the coming week.

Thanks,

Christophe

**Comment by christophediericx** [comment]
Hi Herbstein,

Support for both `ShiftOut`  and `ShiftIn` operations have been added to the ArduinoDriver (version 2.4, you might need to update your referenced nuget package).

A sample call:

`var response = driver.send(new ShiftOutRequest(5, 2, BitOrder.MSBFirst, 0x13)`

Feel free to reopen the ticket if the functionality should not work correctly!

Christophe

**Comment by Herbstein** [comment]
Hi Christophe,

I didn't notice you had replied to the feature request I try and stay active in issues I open, so sorry about that!

I haven't been able to test the update yet (I've been away from my board) but it looks like a solid implementation. Thanks for the added support!

Herbstein

**Comment by christophediericx** [comment]
Hi Herbstein, 

No worries, it can take me a couple of days to respond to issues, too.

Thanks,

Christophe
