### ISSUE TITLE
AnalogRead

### ISSUE THREAD

**Issue by pitt716** [christophediericx/ArduinoDriver#16]
Does anyone know how to read in an analog value to c# from the Arduino UNO using the ArduinoDriver? I am trying to read in the value from a pressure sensor connected to the Arduino and store it as an int in my c# code. Thanks!

**Comment by christophediericx** [comment]
Hi pitt716,

Here is a small code sample that may help you (it should help illustrate the general concept of the library):

```
const int analogPinToRead = 4;
using (var driver = new ArduinoDriver(AttachedArduino, true))
{
    var analogReadResponse = driver.Send(new AnalogReadRequest(analogPinToRead));
    var readValue = analogReadResponse.PinValue;
}

```
