### ISSUE TITLE
Compatibility with Arduino Due .

### ISSUE THREAD

**Issue by ZeusJp** [christophediericx/ArduinoDriver#2]
I wonder if it was already done some testing with Arduino Due to this library.

**Comment by christophediericx** [comment]
Although I have not tested it (I have no Due board) I think it will probably "just work" with a single important exception: the "autobootstrap feature" (the ability for the library to upload it's own listener to the board without requiring any user interaction; this is processor dependent and currently only ATMega328P is supported). 

This means you _should_ be able to use the ArduinoDriver C# library as long as you compile and upload the listener yourself in the Arduino IDE ([here is the source for the listener] (https://raw.githubusercontent.com/christophediericx/ArduinoDriver/master/Source/ArduinoDriver/ArduinoListener/ArduinoListener.ino)). Afterwards, just link the ArduinoDriver nuget package from a C# project, and instantiate a driver without passing true to the constructor, as that is the flag that enables autobootstrap behaviour. For example:

```csharp
const byte digitalPinToRead = 12;
var driver = new ArduinoDriver.ArduinoDriver();
var readPinResponse = driver.Send(new DigitalReadRequest(digitalPinToRead));
```

If you try it out, feel free to comment if everything works as intended for you. Perhaps I'll acquire an Arduino Due board in the coming weeks. If I do, I will definitely implement support for it.
