### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by zombieJesus** [christophediericx/ArduinoDriver#20]
Hi!
Thanks a bunch for this library first off, amazing effort. 
I haven't had much time yet to parse and implement majority of features in this,
is it possible to upload the code to the microcontroller or produce an arduino code from the library?

Thanks in advance.

**Comment by christophediericx** [comment]
Hi,

Thank you for your interest in this library, and sorry for taking so long to respond.

Conceptually, although this library allows one to use C# to communicate with an Arduino (as long as there is a persistent connection), it does not produce code for the microcontroller itself.

What happens is that a listener (in the form of a precompiled Arduino code file) gets autodeployed to the Arduino. This listener then listens on the serial connections (which can be sent to it throught the C# library).  I hope this explanation helps!

Thanks,

Christophe
