### ISSUE TITLE
Support for Arduino Leonardo

### ISSUE THREAD

**Issue by zombieJesus** [christophediericx/ArduinoDriver#21]
Hi,
I was wondering if it would be possible to add support for Leonardo boards.

Thanks!

**Comment by christophediericx** [comment]
Thank you for your interest in this library, and sorry that it took me so long to answer your question.

The Leonardo uses the `AVR-109` protocol (which is implemented already). This means it should be really easy to add support. I currently have no Leonardo, but I just ordered one of Amazon. Once it's here, I'll add support and comment on the ticket. Please give it another 2 to 3 weeks at most.

**Comment by christophediericx** [comment]
Support for Leonardo boards has been added. It might take a couple of minutes for the nuget package to index the very latest version (2.4.2).
