### ISSUE TITLE
Check this library tha I made using yours

### ISSUE THREAD

**Issue by aleGuardiola** [christophediericx/ArduinoDriver#27]
Hello I made a library using your awesome one and I want you to look at the library, sorry for my english is not good https://github.com/aleGuardiola/DynamicDriver

**Comment by christophediericx** [comment]
Hi aleGuardiola,

Thank you for your interest in this library, and sorry it took me so long to respond.

I'm happy you enjoyed the library.

Thanks,

Christophe
