### ISSUE TITLE
Doesn't work with Arduino Nano w/ ATmega328

### ISSUE THREAD

**Issue by laheller** [christophediericx/ArduinoDriver#3]
Driver + Sample after running throw following exception:
"Unable to establish sync after 20 retries!"

But board is OK, because I can program it using Arduino IDE.

**Comment by christophediericx** [comment]
Thank you for notifying me of this issue. At the moment the library has only been tested with Arduino UNO boards (as that was the only one I had available). I ordered a Nano board today, so I'll be able to sort out this compatibility issue over the course of the next weeks (I expect it to just require minor tweaks).

**Comment by christophediericx** [comment]
With the latest version, support for Mega2560 and Nano (R3, Atmega328P based) was added.
