### ISSUE TITLE
Read Analog input

### ISSUE THREAD

**Issue by frank7fan** [christophediericx/ArduinoDriver#8]
Thanks for the great contribution! I am new to the coding world.
Can you give an example how to read an Analog input? I can use Digital WriteRequest to toggle the Digital pin. I saw your Buzzer example. Do you need to define the PinMode first? Thanks!

Frank

**Comment by christophediericx** [comment]
Hi, thank you for your interest in this library.

Analog pins are input only, so you should not need to set the pinMode explicitely.

Here is the simplest (complete) example on how to do an analog read (you might need to change your Arduino model and / or pin number off course):

```
byte analogPin = 3;

var driver = new ArduinoDriver(ArduinoModel.UnoR3, true);
var analogReadResponse = 
    (AnalogReadResponse) driver.Send(new AnalogReadRequest(analogPin));

Console.WriteLine("Pin read: {0}", analogReadResponse.PinRead);
Console.WriteLine("Pin value: {0}", analogReadResponse.PinValue);
```

**Comment by frank7fan** [comment]
Hi Chris, working great! Thanks!
